	SUBROUTINE ATOMIC
	INCLUDE 'SOLDIV.FI' 
C		CONSTRUCT NEUTRAL COOLING, MOMENTUM LOSS & ION SOURCE TERMS
C	FROM NEUTRAL MODEL,FOR USE IN PLASMA PARTICLE BALANCE. 
C	COOLING--ASSUME ALL NEUTRALS ENTER PLASMA W/TEMP TODD COMING OFF DP

	DXLDIV = XLPAR-XLPERP-DELLT
	AD = BETAG*DELLT*DELNV*EPDIV
	ADIV = BETAG*DXLDIV*DELNV*EPDIV
	ASOL = BETAG*XLPERP*DELNV
	AXPT = YXPT*DELXPT
	ERECION = 13.6 
	CSD = SQRT(2.*XK*TD/XMASS) 
 	CALL MOLECULE 
	RATNENI2D=(1.+ IZINJECT*FZINJECT+4.*FBE+2.*FHE+
     2			IZINTRIN*FZINTRIN)**2
	XNSOL = HNSOL*XNSEP 
	XNDIV = HNDIV*XNSEP + (1.-HNDIV)*XND
	TSOL =  HTSOL*TSEP  
	TDIV =  HTDIV*TSEP  + (1.-HTDIV)*TD
	VSOL =  HVSOL*0.0   
	VDIV =  HVDIV*0.0   + (1.-HVDIV)*CSD
	FDIV = 1.-HNDIV
	FCOLDR = XNCOLDD/XNOD 
	TNEUTR = FCOLDR*TODD + (1.-FCOLDR)*TD 

C	NET ION SOURCE
	DNATOLD = DNAT 
	DELNS = DELN*EPDIV/SIN(THETA)
C	IONIZATION-RECOMBINATION+DISSOCIATION ION PRODUCTION
	DND = YIONREC 
	DNDIV = YIONDIV
C		FRACT FIN OF IONS CREATED IN SOL DIFFUSE INTO CORE
	DNSOL = (YIONSOL+YIONSOLXPT)*(1.-FIN)
C	XPT CONTRIBUTION INCLUDED IN SOL	
	DNAT= DND + DNDIV + DNSOL
C	ACTUAL IONIZATION RATE
	DNIOND =YIONREC+ XND*SVRECD*XND*AD	-
	2		GAMZERO*DELNS*HDISP	 
c	DNION = DNIOND + YIONDIV + YIONSOL 

C	FREQUENCIES FOR DIVERTER STABILITY CALCULATION
	RNN	= FLUXPART*XLPERP/(XNSEP*DELNV)	
	XMDIV = 0.5*(1.+XMSOL) 
	FREQIONREC = (DND/(XND*DELNV*EPDIV)) + (DNDIV/(XNDIV*DELNV*EPDIV))
     2			 + (DNSOL/(XNSEP*DELNV))/BETAG
      FREQIOND = (DNIOND/(XND*DELNV*EPDIV))/BETAG
	FREQRECD = (SVRECD*XND*AD/(DELNV*EPDIV))/BETAG
	FREQION = FREQIONREC + FREQRECD 
	FREQIONE = ((EIOND/TD)*(DNIOND/(XND*DELNV*EPDIV))
     2 		 + (EIONDIV/TDIV)*(DNDIV/(XNDIV*DELNV*EPDIV))
     3         + (EIONSOL/TSOL)*(DNSOL/(XNSEP*DELNV)))/BETAG
	FREQIONM = ((DNIOND/(XND*DELNV*EPDIV))
     2 		 + (XMDIV**2)*(DNDIV/(XNDIV*DELNV*EPDIV))
     3         + (XMSOL**2)*(DNSOL/(XNSEP*DELNV)))/BETAG 
	FREQIONDIV = (DNDIV/(XNDIV*DELNV*EPDIV))/BETAG
 	FREQIONSOL =  (DNSOL/(XNSEP*DELNV))/BETAG 
	FREQATD = (FCRATD/(XND*DELNV*EPDIV))/BETAG
	FREQATDIV = (FCRATDIV/(XNDIV*DELNV*EPDIV))/BETAG
	FREQATSOL =	(FCRATSOL/(XNSOL*DELNV))/BETAG
	FREQAT = FREQATD + FREQATDIV + FREQATSOL
	FREQATM = FREQATD + (XMDIV**2)*FREQATDIV + (XMSOL**2)*FREQATSOL
	CONDUCTI = (7.*XKAPPA*(TD**2.5)/(XK*XND))*
     2       		(FREQATD+2.*FREQIOND-FREQRECD) +
	3		   (7.*XKAPPA*(TDIV**2.5)/(XK*XNDIV))*
     4			(FREQATDIV +2.*FREQIONDIV)*(XMDIV**2) +
	5		   (7.*XKAPPA*(TSOL**2.5)/(XK*XNSOL))*
	6			(FREQATSOL +2.*FREQIONSOL-2.*RNN)*(XMSOL**2)

C	AVERAGED TEMPERATURE & DENSITY DERIVATIVE TERMS
C	DATA--TEMPERATURE & DENSITY DERIVATIVES OF COLLISION FREQUENCIES
	
	DIONDT1T10   = 1.1
	DIONDT10T100 = 0.6
	DRECDT1T10   =-1.06 
	DATDT1T10    = 0.48
	DATDT10T100  = 0.45
C	TERMS
	IF(TD.LT.10.) THEN
	DFREQRECDT = FREQRECD*DRECDT1T10 
 	DFREQIONDT = ((DND*BETAG/(XND*DELNV*EPDIV)+FREQRECD)*DIONDT1T10 +
	1			  (DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2			  (DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100)   
	DFREQIONDTM = ((DND*BETAG/(XND*DELNV*EPDIV)+FREQRECD)*DIONDT1T10 +
     1	(XMDIV**2)*(DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2	(XMSOL**2)*(DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100)   
	DFREQIONDTE = ((EIOND/TD)*(DND*BETAG/(XND*DELNV*EPDIV))+FREQRECD)*
     1				DIONDT1T10 +  (EIONDIV/TDIV)*
 	1			  (DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2    (EIONSOL/TSOL)*(DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100   
	DFREQATDT =	FREQATD*DATDT1T10 + 
     1			FREQATDIV*DATDT10T100 +
     2			FREQATSOL*DATDT10T100 
	DFREQATDTM = FREQATD*DATDT1T10 + 
     1			 (XMDIV**2)*FREQATDIV*DATDT10T100 +
     2			 (XMSOL**2)*FREQATSOL*DATDT10T100  
	ELSE 
     	DFREQIONDT = ((DND*BETAG/(XND*DELNV*EPDIV)+FREQRECD)*DIONDT10T100+
 	1			  (DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2			  (DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100)   
	DFREQIONDTM = ((DND*BETAG/(XND*DELNV*EPDIV)+FREQRECD)*DIONDT10T100 
     1  +	(XMDIV**2)*(DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2	(XMSOL**2)*(DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100)   
	DFREQIONDTE = ((EIOND/TD)*(DND*BETAG/(XND*DELNV*EPDIV))+FREQRECD)*
     1				DIONDT10T100 +  (EIONDIV/TDIV)*
 	1			  (DNDIV*BETAG/(XNDIV*DELNV*EPDIV))*DIONDT10T100 +
     2    (EIONSOL/TSOL)*(DNSOL*BETAG/(XNSEP*DELNV))*DIONDT10T100   
	DFREQATDT =	FREQATD*DATDT10T100 + 
     1			FREQATDIV*DATDT10T100 +
     2			FREQATSOL*DATDT10T100 
	DFREQATDTM = FREQATD*DATDT10T100 + 
     1			 (XMDIV**2)*FREQATDIV*DATDT10T100 +
     2			 (XMSOL**2)*FREQATSOL*DATDT10T100  

	ENDIF 

C		COOLING RATES	
C	IONIZATION COOLING MINUS VOLUME RECOMBINATION RECOVERY OF EION
C	WALL COOLING CALCULATED IN ITERATION LOOP IN DIVERT2 

C		TEMPERATURES OF NEUTRALS RECYCLING INTO DIV AND SOL AND REC
C			EMOL IS ENERGY OF ATOMS FROM MOLECULAR DISSOCIATION
	EMOL = 2.
C			TAKING INTO ACCOUNT THE SHEATH ACCELERATION OF IONS RECYCLING AS NEUTRALS
	FQ = GAMZEROM/(XND*CSD*BETAG*SIN(THETA))
	TDQ = ((3.+FQ)/(1.+FQ))*TD
	CALL REFLECTION(TDQ,TNDQ,FMOLDQ)
	CALL REFLECTION(TD,TND,FMOLD)
	CALL REFLECTION(TDIV,TNDIV,FMOLDIV)
	CALL REFLECTION(TSOL,TNSOL,FMOLDSOL)
C	TNSOLA = 0.5*TNSOL*(1.0 + EXP(-1.*DELRATNT)) 
C 	TNDIVA = 0.5*TNDIV*(1.0 + EXP(-1.*DELRATNT)) 

C		TAV FOR RADIALLY LOSS IONS REFLECTED AS NEUTRALS 
C	TNRAD = (XNSOL*TNSOL*XLPERP +XNDIV*TNDIV*DXLDIV + XND*TND*DELLT)/
C     2	   (XNSOL*XLPERP +	XNDIV*DXLDIV + XND*DELLT) 
C		TAV FOR NEUTRALS ESCAPING RECYCLE & divertor REGIONS INTO PRIVATE FLUX REGION	
C	TDPF= (((TOD2PF*TND + (1.-TOD)*GPF*TD)/(TOD2PF + (1.-TOD)*GPF))*
C     2 	GAMR2PF*DELLT  +  TNDIVA*GAMDIV2PF*DXLDIV)/
C	3	(GAMR2PF*DELLT  +  GAMDIV2PF*DXLDIV)
C		TAV FOR NEUTRALS ESCAPING RECYCLE & DIVERTOR REGIONS INTO DIVERTOR PLENUM
C	TDPL= (((TOD2PL*TND + (1.-TOD)*GPL*TD)/(TOD2PL + (1.-TOD)*GPL))*
C	2 	GAMR2PL*DELLT  +  TNDIVA*GAMDIV2PL*DXLDIV)/
C	3	(GAMR2PL*DELLT  +  GAMDIV2PL*DXLDIV)   


C		NEUTRALS ESCAPING PRIVATE FLUX REGION INTO PLASMA REGION
C	(assume neutrals traverse pf region between div legs w/o wall hit)

	FUELPL = FUELPLIN + FUELPLOUT 
C	CALL REFLECTION(TDPF,TNDPF,FMOLPF)
	TPF = ((0.5*FUELPF/(6.28*RMAJOR))*TSOR + (GAMDIV2PF*DXLDIV*
	2      BETAG*TNDIV + GAMR2PF*DELLT*BETAG*TND))/
	3      (0.5*(FUELPF/(6.28*RMAJOR)) + GAMDIV2PF*DXLDIV*BETAG
	4      + GAMR2PF*DELLT*BETAG)
C		NEUTRALS ESCAPING DIVERTOR PLENUM REGION INTO PLASMA 
c	(assumes all non-source particles have bounced off wall)
	CALL REFLECTION(TDPL,TNDPL,FMOLPL)
 	TPL = ((FUELPLOUT/(6.28*RMAJOR))*TSOR + GAMDIV2PL*DXLDIV*
 	2      BETAG*TNDIV + GAMR2PL*DELLT*BETAG*TND + 
     4	  ALPHASOL*GAMOUTPL*XLUP1*TNSOL)/
	3      ((FUELPLOUT/(6.28*RMAJOR)) + GAMDIV2PL*DXLDIV*BETAG
	4      + GAMR2PL*DELLT*BETAG + ALPHASOL*GAMOUTPL*XLUP1)

C		NEUTRAL ENTERING PLASMA FROM SOL PLENUM REGION
	TSPL=((FUELMP/(6.28*RMAJOR))*TSOR  +
     2	ALPHASOL*GAMOUTSPL*(BETAG*XLPERP-XLUP1)*TNSOL)/
     3	(FUELMP/(6.28*RMAJOR) +
     4	ALPHASOL*GAMOUTSPL*(BETAG*XLPERP-XLUP1))
C		NEUTRALS IN SOL

C	TNSOL = TSOL*(1./(1.+DELRATNT/Y))*(1.-EXP(-1.*(Y+DELRATNT)))/
C	2		(1.-EXP(-1.*Y))  
	Z = BETAG*DELLT
	ZQ = BETAG*DELX
C		NEUTRALS ENTERING PLASMA FROM DIVERTOR PUMP REGION
	GAMPUMP1 = (GEOM11*Z*GAMR2PL + GEOM21*ZQ*GAMDIV2PL +
     2			(APL1*GAMOUTPL + APF1*GAMOUTPF)*YPUMP1)/YPUMP1
	TPUMP = ((GEOM11*Z*GAMR2PL*TNDIV + GEOM21*ZQ*GAMDIV2PL*TNDPL +
     2		(APL1*GAMOUTPL*TPL + APF1*GAMOUTPF*TPF)*YPUMP1)/YPUMP1)/
	3		GAMPUMP1

C	*****	RECYCLING REGION  ***********
 
c	IONIZATION COOLING
	DQRION = (1.-REABSORBD)*(EIOND)*XK*DNIOND
C	RECOMBINATION HEATING
	DQRRECOM = AD*(XND*XND*(FREC*ERECION)*SVRECD*XK)/SQRT(RATNENI2D)

C	NET COOLING DUE TO RECYCLING NEUTRALS AT DIVERTOR PLATE
	DQRATDP = (DELN*EPDIV/SIN(THETA))*(GAMZEROM*1.5*TD -
     2  GAMZERO*(EMOL*FMOL + 0.5*TD*(1.-FMOL)))*XK
	dqratdp = wallmult*dqratdp 
C     2 (GAMZERO/(RNN*RWDP))*(DELN*EPDIV/SIN(THETA))*1.5*XK*TND 
C	NET COOLING DUE TO EXCHANGE OF NEUTRALS BETWEEN RECYCLING REGION
C     AND PRIVATE FLUX & DIV PLENUM REGIONS
	DQRATDW = (GAMR2PF+GAMR2PL)*DELLT*BETAG*1.5*XK*TD -
	2  		  (GAMOUTPF*TPF+GAMOUTPL*TPL)*DELLT*BETAG*1.5*XK -
	3		  CPUMP11*GAMPUMP1*1.5*XK*TPUMP*YPUMP1 +
     4		  DELPUMP1*GAMOUTPF*TPF*1.5*XK 	
	dqratdw = wallmult*dqratdw 

C	TOTAL ATOMIC COOLING IN RECYCLING REGION
	DQR = DQRION + DQRATDP + DQRATDW - DQRRECOM
	DQRAT = DQRATDP + DQRATDW - DQRRECOM
C	*****	DIVERTOR CHANNEL  ***********
C	IONIZATION COOLING	 
 	DQDIVION= (1.-REABSORBDIV)*(EIONDIV)*XK*YIONDIV
C	RECOMBINATION HEATING
      DQDIVREC = ADIV*(XNDIV*XNDIV*(FREC*ERECION)*XK*SVRECDIV)
C     NET COOLING DUE TO RECYCLING OF NEUTRALS BETWEEN DIVERTOR CHANNEL
C	AND DIVERTOR PLENUM AND PRIVATE FLUX REGIONS
	DQDIVAT  = 	1.5*XK*TNDIV*(GAMDIV2PF+GAMDIV2PL)*DXLDIV*BETAG -
     2			1.5*XK*(GAMOUTPF*TPF+GAMOUTPL*TPL)*DXLDIV*BETAG 
	dqdivat = wallmult*dqdivat 
C		TOTAL DIVERTOR CHANNEL ATOMIC COOLING				 
	DQDIV = DQDIVION + DQDIVAT-DQDIVREC
C	*******  SOL	*********************	 
C	IONIZATION COOLING
	DQSOLION = (1.-REABSORBSOL)*(EIONSOL)*XK*(YIONSOL + YIONSOLXPT)
C	RECOMBINATION HEATING
	DQSOLREC = ASOL*(XNSOL*XNOSOL*(FREC*ERECION)*XK*SVRECSOL)
C	NET COOLING DUE TO EXCHANGE WITH SOL PLENUM
	DQSOLAT = 1.5*XK*(TNSOL*ALPHASOL-TSPL)*GAMOUTSPL*
	2			(XLPERP*BETAG-XLUP1)
	dqsolat = wallmult*dqsolat 
C	COOLING DUE TO NET INWARD FLOW OF NEUTRALS ACROSS SEPARATRIX
	DQINSOL = 1.5*XK*(TNSOL-ALPHASEP*TBAR)*(FLUXNEUTIN*(XLPERP*BETAG-
	2		0.5*DELXPT) + FLUXNEUTINXPT*0.5*DELXPT)
C	HEATING BY CORE IONIZATION RADIATION
	fsolabsorb = 0.0
	DQSOLCORION = fsolabsorb*(PIONCORE/AP)*XLPERP	 
C		TOTAL SOL ATOMIC COOLING
	DQSOL = DQSOLION + DQSOLAT - DQSOLREC + DQINSOL - DQSOLCORION

c	condiv = 2 for SN and = 4 for DN divertor
	condiv = 2.
	if(ioptdiv.eq.2) condiv = 4. 
C	TOTAL ATOMIC COOLING
	DQAT = DQR + DQDIV + DQSOL
	WALLFRAC = 1.- DQINSOL/DQAT
C	TOTAL  NET IONIZATION COOLING - RECOMBINATION HEATING
	DQION = DQRION + DQDIVION + DQSOLION
	DQREC = DQRRECOM + DQDIVREC + DQSOLREC
	PION = condiv*6.2832*RMAJOR*(DQION - DQREC)
C	TOTAL NET TRANSFERRED TO WALL BY ATOMIC RECYCLING
	DQWALL = DQRATDW + DQDIVAT + DQSOLAT
c	PWALL = condiv*6.2832*RMAJOR*DQWALL
C	TOTAL NET TRANSFERRED TO DIVERTOR PLATE BY ATOMIC RECYCLING
c	PDPAT = condiv*6.2832*RMAJOR*DQRATDP	 
 
C	MOMENTUM LSS
	DMATOLD = DMR 
	DMR=XMASS*CSD*BETAG*FSHEATH*FCRATD
	DMR = DMR + XMASS*CSD*BETAG*FSHEATH*AD*(XND*SVRECD)*XND
	DMDIV =	XMASS*VDIV*FCRATDIV
	DMSOL =	XMASS*VSOL*FCRATSOL
	DMAT = DMR + DMDIV + DMSOL
C	ATOMIC FIRST-COLLISON SCAT+CX RATE PLUS RECOM RATE--FOR PLASMA BALANCE
	RRATD = FCRATD + AD*(XND*SVRECD)*XND
	RRATDIV = FCRATDIV
	RRATSOL = FCRATSOL

C	IONIZATION RATE FOR PLASMA BALANCE
	RRIOND = YIONREC
	RRIONDIV = YIONDIV
	RRIONSOL = YIONSOL 

C		QUANTITIES FOR DENSITY & MOMENTUM BALANCES
C		MAX PARALLEL DISTANCE TO USE DP VALUES IS 10 cm
	ISWIT = 0
	IF(DELLT.LE.1E-1) GOTO 50 	
	ISWIT = 1
	DELLTOLD = DELLT
	DELLT= 1E-1
50	CONTINUE 

      IF(ISWIT.EQ.0) GOTO 100	 
	DELLT = DELLTOLD
	DXLDIV = XLPAR-XLPERP-DELLT
100	RETURN
	END