	SUBROUTINE PUMPGEOMOUT
	INCLUDE 'SOLDIV.FI'
C		CALCULATES PUMP GEOMETRY FACTORS FOR OUTBOARD PUMPS
C	DETERMINES THE 'CASE' FOR THE SEPARATRIX STRIKE POINT VIS-A-VIS PUMP
	THETA1 = ATAN(ABS((ZSEP1-ZX)/(RSEP1-RX)))
	DELX1 = (XLPAR1-XLPERP1-DELLT1)
	IF(RSEP1.GT.RDOME) GOTO 100
C		CASE 5 RSEP < RDOME  STRIKE POINT ON DOME	 
	IOUTCASE = 5
	THETA1 = THETA1 + PHIDOME
	DELNS = EPDIV1*DELN1/SIN(THETA1) 
	GEOM1 = 0.0
	GEOM2 = 0.0
	HGEOM1 = 0.0
	HGEOM2 = 0.0
	GOTO 1000
100	DELNS = EPDIV1*DELN1/SIN(THETA1) 
	XSEP0 = XRING - DELNS
	IF(RSEP1.GT.XSEP0) GOTO 200
C		CASE 1  XDOME<RSEP1<XSEP0  STRIKES ON FLOOR & NOT UNDER RING
	IOUTCASE = 1 
	X1 = RSEP1 + DELNS - 0.5*BETAG*DELLT1*COS(THETA1)
	X2 = (X1 + 0.5*BETAG*DELLT1*SIN(THETA1)*XRING/YPUMP1)/
     2	 (1.0 + 0.5*BETAG*DELLT1*SIN(THETA1)/YPUMP1)
      PHI1 = ATAN(YPUMP1/(XRING - X2))
	PHI2 = ATAN((YPUMP1 - 0.5*BETAG*DELLT1*SIN(THETA1))/(XRING - X1)
	GEOM1 = (PHI1 + PHI2)/3.14159
	X3 = RSEP1 + DELNS - BETAG*(DELLT1 + 0.5*DELX1)*COS(THETA1)
	X4 = (X3 + BETAG*(DELLT1 + 0.5*DELX1)*SIN(THETA1)*XRING/YPUMP1)/
	2	 (1.0 + BETAG*(DELLT1 + 0.5*DELX1)*SIN(THETA1)/YPUMP1)
	PHI3 = ATAN(YPUMP1/(XRING - X4))
	PHI4 = ATAN((YPUMP1-BETAG*(DELLT1 + 0.5*DELX1)*SIN(THETA1))/
	2			(XRING - X3)
      GEOM2 = (PHI3 + PHI4)/3.14159
	X5 = RSEP1 + DELNS - BETAG*DELLT1*COS(THETA1)
	X6 = (XRING + 0.5*YPUMP1*X5/(BETAG*DELLT1*SIN(THETA1)))/
     2	 (1.0 + 0.5*YPUMP1*X5/(BETAG*DELLT1*SIN(THETA1)))
      PHI5 = ATAN((BETAG*DELLT1*SIN(THETA1)- 0.5*YPUMP1)/(XRING-X5))
	PHI6 = ATAN(0.5*YPUMP1/(XRING - X6))
	HGEOM1 = (PHI5 + PHI6)/3.14159
	HGEOM2 = 1.0 - HGEOM1
	GOTO 1000
200	XSEP1 = (YPUMP1/TAN(THETA1)) + XRING - DELNS
	IF(RSEP1.GT.XSEP1) GOTO 300
C		CASE 2  XSEP0<RSEP1<XSEP1  STRIKES UNDER RING BUT NOT SCRAPED OFF
	IOUTCASE = 2
	X1 = RSEP1 + DELNS - 0.5*BETAG*DELLT1*COS(THETA1)
 	PHI2 = ATAN((YPUMP1 - 0.5*BETAG*DELLT1*SIN(THETA1))/(XRING - X1)
	GEOM1 = (PHI2 + THETA1)/3.14159
	X3 = RSEP1 + DELNS - BETAG*(DELLT1 + 0.5*DELX1)*COS(THETA1)
	PHI4 = ATAN((YPUMP1-BETAG*(DELLT1 + 0.5*DELX1)*SIN(THETA1))/
	2			(XRING - X3)
	GEOM2 = (PHI4 + THETA1)/3.14159
	GEOM2P = (YPUMP1-BETAG*DELLT1*SIN(THETA1))/
	2		  (BETAG*DELX1*SIN(THETA1))
	IF(GEOM2P.GT.GEOM2) GEOM2 = GEOM2P
	HGEOM1 = BETAG*DELLT1*SIN(THETA1)/YPUMP1
	HGEOM2 = 1.0 - HGEOM1		 
				 





c	**************TAKE EVERYTHING BELOW THIS OUT************************
C		CALCULATES PUMP SOLID ANGLE GEOMETRIC FACTORS
	DELNS = EPDIV*DELN/SIN(THETA) 
	ANGLE = 3.1416 - THETA
	DELNZ = 0.02
	DXPUMP = XRING - (XSEP+DELNZ) 
	IF(DXPUMP.GT.0.0) GOTO 5
C	CONDITION FOR ENTIRE RIGHT SURFACE RECYCLE REGION UNDER RING
      IF(ABS(DXPUMP).GE.(YPUMP/TAN(ANGLE))) GOTO 60 
C	GEOMETRIC FACTOR FOR NEUTRALS FROM RECYCLING REGION	
5	DELTA = BETAG*DELLT/5.
	XL = -0.5*DELTA
	GEOM1 = 0.0
C	STRIKE POINT TO LEFT OF RING
	DO 25 N = 1,5
	XL = XL + DELTA
	XMAX = (YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE))
15	XMIN = ABS((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF(DXPUMP.LT.0.0)
     2  XMIN = ABS((YPUMP-XL*SIN(ANGLE))/ABS(ABS(DXPUMP)-XL*COS(ANGLE)))	 
	PHIMIN = ATAN(XMIN)
	IF(DXPUMP.LT.0.0.AND.XL*SIN(ANGLE).LT.YPUMP) PHIMIN=3.1416-PHIMIN
	PHIMAX = ATAN(XMAX)
	IF(DXPUMP.LT.0.0) PHIMAX = ANGLE 
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	IF(XL*SIN(ANGLE).GT.YPUMP) EPUMP = (PHIMAX-PHIMIN)/3.1416
	GEOM1 = GEOM1 + EPUMP*DELTA
25	CONTINUE
	GEOM1 = GEOM1/(BETAG*DELLT)

C	GEOMETRICAL FACTOR FOR NEUTRALS FROM DIVERTOR CHANNEL
40	DELTA = BETAG*(XLPAR-XLPERP-DELLT)/10.
	GEOM2 = 0.0
C	STRIKE POINT TO LEFT OF RING		 
	XL = BETAG*DELLT - 0.5*DELTA
	DO 50 N = 1,10
 	XL = XL + DELTA
	XMAX = (YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE))
	XMIN = ABS((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF(DXPUMP.LT.0.0)
     2  XMIN=ABS((YPUMP-XL*SIN(ANGLE))/ABS(ABS(DXPUMP) - XL*COS(ANGLE)))	 
	PHIMIN = ATAN(XMIN)
	IF(DXPUMP.LT.0.0.AND.XL*SIN(ANGLE).LT.YPUMP) PHIMIN=3.1416-PHIMIN
      PHIMAX = ATAN(XMAX) 
	IF(DXPUMP.LT.0.0) PHIMAX = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	IF(XL*SIN(ANGLE).GT.YPUMP) EPUMP = (PHIMAX-PHIMIN)/3.1416
	GEOM2 = GEOM2 + EPUMP*DELTA
50	CONTINUE
	GEOM2 = GEOM2/(BETAG*(XLPAR-XLPERP-DELLT))
	GOTO 75
C	SEPARATRIX + EP*DELN PASSES THROUGH RING--CASE 5
60	GEOM1 = 1.0 
	GEOM2 = ((YPUMP/SIN(ANGLE))-BETAG*DELLT)/
	2        (BETAG*(XLPAR-XLPERP-DELLT))		
75	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
	IF(HGEOM1.GT.1.0) HGEOM1 = 1.0 
	HGEOM2 = 1. - HGEOM1 

	

	  RETURN
	 
	  END
