	SUBROUTINE PUMPGEOMNEW
	INCLUDE 'SOLDIV.FI'
C		CALCULATES PUMP SOLID ANGLE GEOMETRIC FACTORS
	delnz = deln
      deln = 0.02*sin(angle)/epdiv 
	ANGLE = 3.1416 - THETA 
      DELNS = EPDIV*DELN/SIN(ANGLE) 
	DXPUMP = XRING - (XSEP+DELNS)
	
	XSEP1 = XRING - YPUMP*COT(ANGLE) - DELNS
	XSEP2 = XRING - DELNS
	XSEP3 = XRING + YPUMP*COT(ANGLE) - DELNS
	XSEP4 = XRING + YPUMP*COT(ANGLE) 
C	SELECT REGION
	IF(XSEP.GE.XSEP1) GOTO 100
C		REGION 1  XSEP < XSEP1		
C	NEUTRALS FROM RECYCLING OR DIVERTOR PLASMA CAN REFLECT FROM FLOOR AND MISS PUMP				
C	GEOMETRIC FACTOR FOR NEUTRALS FROM RECYCLING REGION INTO PUMP	
	DELTA = BETAG*DELLT/10.
	XL = -0.5*DELTA
	GEOM1 = 0.0
	DO 25 N = 1,10
	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	PHIMIN = ATAN((YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	EPUMP = (PHIMIN+PHIMAX)/3.1416
 	GEOM1 = GEOM1 + EPUMP*DELTA
25	CONTINUE
	GEOM1 = GEOM1/(BETAG*DELLT)
C	GEOMETRICAL FACTOR FOR NEUTRALS FROM DIVERTOR CHANNEL INTO PUMP
	DELTA = BETAG*(XLPAR-XLPERP-DELLT)/10.
	GEOM2 = 0.0
	XL = BETAG*DELLT - 0.5*DELTA
	DO 50 N = 1,10
 	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	PHIMIN = ATAN((YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	GEOM2 = GEOM2 + EPUMP*DELTA
50	CONTINUE
	GEOM2 = GEOM2/(BETAG*(XLPAR-XLPERP-DELLT))
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO RECYCLING REGION
	DY = YPUMP/10.
	HGEOM1 = 0.0
      Y = -0.5*DY
	DO 60 N = 1,10
	Y = Y + DY
	ZY=COS(ANGLE)
	ZZ=SIN(ANGLE)
	PSIMAX = ATAN((BETAG*DELLT*SIN(ANGLE) - Y)/
	2		(DXPUMP+BETAG*DELLT*COS(ANGLE))) 
	PSIMIN = ATAN((BETAG*DELLT*SIN(ANGLE) + Y)/
 	2		(DXPUMP+BETAG*DELLT*COS(ANGLE))) 
      GPUMP = (PSIMIN + PSIMAX)/3.1416 
	HGEOM1 = HGEOM1 + GPUMP*DY
60	CONTINUE
	HGEOM1 = HGEOM1/YPUMP
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO DIVERTOR PLASMA
	HGEOM2 = 1. - HGEOM1 
	GOTO 500
100	IF(XSEP.GE.XSEP2) GOTO 200
C		REGION 2	XSEP1 < XSEP < XSEP2
C	NEUTRALS FROM RECYCLE OR DIVERTOR REFLECT FROM FLOOR INTO PUMP, 
C	BUT RECYLE REGION NOT UNDER RING 
      DELTA = BETAG*DELLT/10.
	XL = -0.5*DELTA
	GEOM1 = 0.0
	DO 125 N = 1,10
	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	PHIMIN = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
 	GEOM1 = GEOM1 + EPUMP*DELTA
125	CONTINUE
	GEOM1 = GEOM1/(BETAG*DELLT)
C	GEOMETRICAL FACTOR FOR NEUTRALS FROM DIVERTOR CHANNEL INTO PUMP
	DELTA = BETAG*(XLPAR-XLPERP-DELLT)/10.
	GEOM2 = 0.0
	XL = BETAG*DELLT - 0.5*DELTA
	DO 150 N = 1,10
 	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	PHIMIN = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	GEOM2 = GEOM2 + EPUMP*DELTA
150	CONTINUE
	GEOM2 = GEOM2/(BETAG*(XLPAR-XLPERP-DELLT))
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO RECYCLING REGION
c	DY = YPUMP/10.
c 	HGEOM1 = 0.0
c      Y = -0.5*DY
c	DO 160 N = 1,10
c	Y = Y + DY
c	PSIMAX = ATAN((BETAG*DELLT*SIN(ANGLE) - Y)/
c	2		(DXPUMP+BETAG*DELLT*COS(ANGLE))) 
c	PSIMIN = ATAN((BETAG*DELLT*SIN(ANGLE) + Y)/
c 	2		(DXPUMP+BETAG*DELLT*COS(ANGLE))) 
c	PSIMIN2 = ATAN(Y/DXPUMP)
C	IF(PSIMIN2.GT.PSIMIN) PSIMIN = PSIMIN2 
c      GPUMP = (PSIMIN + PSIMAX)/3.1416 
c	HGEOM1 = HGEOM1 + GPUMP*DY
c160	CONTINUE
	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
	IF(BETAG*DELLT*SIN(ANGLE).GE.YPUMP) HGEOM1 = 1.0
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO DIVERTOR PLASMA
180	HGEOM2 = 1. - HGEOM1 
	GOTO 500
C		REGION 3	XSEP2 < XSEP < XSEP3	
C	RECYCLING REGION PARTIALLY UNDER RING, BUT PUMP ENTRANCE NOT CLOSED BY PLASMA
C	GEOMETRIC FACTOR FOR NEUTRALS FROM RECYCLING REGION INTO PUMP	
200	IF(XSEP.GE.XSEP3) GOTO 300	
      DELTA = BETAG*DELLT/10.
	XL = -0.5*DELTA
	GEOM1 = 0.0
	DO 225 N = 1,10
	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF((DXPUMP + XL*COS(ANGLE)).LT.0.0) PHIMAX = -1.0*PHIMAX
	PHIMIN = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
 	GEOM1 = GEOM1 + EPUMP*DELTA
225	CONTINUE
	GEOM1 = GEOM1/(BETAG*DELLT)
C	GEOMETRICAL FACTOR FOR NEUTRALS FROM DIVERTOR CHANNEL INTO PUMP
	DELTA = BETAG*(XLPAR-XLPERP-DELLT)/10.
	GEOM2 = 0.0
	XL = BETAG*DELLT - 0.5*DELTA
	DO 250 N = 1,10
 	XL = XL + DELTA
	PHIMAX = ATAN((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF((DXPUMP + XL*COS(ANGLE)).LT.0.0) PHIMAX = -1.0*PHIMAX
	PHIMIN = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	GEOM2 = GEOM2 + EPUMP*DELTA
250	CONTINUE
	GEOM2 = GEOM2/(BETAG*(XLPAR-XLPERP-DELLT))
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO RECYCLING REGION
c	YRING = -1.0*DXPUMP*TAN(ANGLE)
c	IF(YRING.LT.BETAG*DELLT*SIN(ANGLE)) GOTO 275
c	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
c	GOTO 280 
c275	DY = (YPUMP-YRING)/10.
c	GAMMA = 0.0
c      Y = -0.5*DY
c	DO 260 N = 1,10
c	Y = Y + DY
c	PSI = -1.0*ATAN((DXPUMP+BETAG*DELLT*COS(ANGLE))/
c	2		(BETAG*DELLT*SIN(ANGLE) - Y)) 
c	GPUMP = (PSI)/3.1416 
c	GAMMA = GAMMA + GPUMP*DY
c260	CONTINUE
c	GAMMA = GAMMA/(YPUMP-YRING) 
c	HGEOM1 = (YRING/YPUMP) + (1. - YRING/YPUMP)*GAMMA 
	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
	IF(BETAG*DELLT*SIN(ANGLE).GE.YPUMP) HGEOM1 = 1.0
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP TO DIVERTOR PLASMA
280	HGEOM2 = 1. - HGEOM1 
	GOTO 500
300	IF(XSEP.GE.XSEP4) GOTO 400
C		REGION 3 XSEP3 < XSEP < XSEP4
C	PUMP ENTRANCE CLOSED BY PLASMA, BUT SEPARATRIX NOT STRIKING RING
C	GEOMETRY FACTOR FOR NEUTRALS FROM RECYCLING REGION INTO PUMP

	GEOM1 = YPUMP/(BETAG*DELLT*SIN(ANGLE))
	IF(BETAG*DELLT*SIN(ANGLE).LE.YPUMP) GEOM1 = 1.0
C	GEOMETRY FACTOR FOR NEUTRALS FROM DIVERTOR PLASMA INTO PUMP
	GEOM2 = (YPUMP - BETAG*DELLT*SIN(ANGLE))/
	2		(BETAG*(XLPAR-XLPERP-DELLT)*SIN(ANGLE))
	IF(BETAG*DELLT*SIN(ANGLE).GE.YPUMP) GEOM2 = 0.0		 
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP INTO RECYCLING REGION
	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
	IF(BETAG*DELLT*SIN(ANGLE).GE.YPUMP) HGEOM1 = 1.0
C	GEOMETRY FACTOR FOR NEUTRALS FROM PUMP INTO DIVERTOR PLASMA
	HGEOM2 = 1.0 - HGEOM1
400	CONTINUE	
500	continue
	deln = delnz 
	RETURN
	END