	SUBROUTINE PUMPGEOMOLD
	INCLUDE 'SOLDIV.FI'
C		CALCULATES PUMP SOLID ANGLE GEOMETRIC FACTORS
	DELNS = EPDIV*DELN/SIN(THETA) 
	ANGLE = 3.1416 - THETA
	DELNZ = 0.02
	DXPUMP = XRING - (XSEP+DELNZ) 
	IF(DXPUMP.GT.0.0) GOTO 5
C	CONDITION FOR ENTIRE RIGHT SURFACE RECYCLE REGION UNDER RING
      IF(ABS(DXPUMP).GE.(YPUMP/TAN(ANGLE))) GOTO 60 
C	GEOMETRIC FACTOR FOR NEUTRALS FROM RECYCLING REGION	
5	DELTA = BETAG*DELLT/5.
	XL = -0.5*DELTA
	GEOM1 = 0.0
C	STRIKE POINT TO LEFT OF RING
	DO 25 N = 1,5
	XL = XL + DELTA
	XMAX = (YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE))
15	XMIN = ABS((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF(DXPUMP.LT.0.0)
     2  XMIN = ABS((YPUMP-XL*SIN(ANGLE))/ABS(ABS(DXPUMP)-XL*COS(ANGLE)))	 
	PHIMIN = ATAN(XMIN)
	IF(DXPUMP.LT.0.0.AND.XL*SIN(ANGLE).LT.YPUMP) PHIMIN=3.1416-PHIMIN
	PHIMAX = ATAN(XMAX)
	IF(DXPUMP.LT.0.0) PHIMAX = ANGLE 
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	IF(XL*SIN(ANGLE).GT.YPUMP) EPUMP = (PHIMAX-PHIMIN)/3.1416
	GEOM1 = GEOM1 + EPUMP*DELTA
25	CONTINUE
	GEOM1 = GEOM1/(BETAG*DELLT)

C	GEOMETRICAL FACTOR FOR NEUTRALS FROM DIVERTOR CHANNEL
40	DELTA = BETAG*(XLPAR-XLPERP-DELLT)/10.
	GEOM2 = 0.0
C	STRIKE POINT TO LEFT OF RING		 
	XL = BETAG*DELLT - 0.5*DELTA
	DO 50 N = 1,10
 	XL = XL + DELTA
	XMAX = (YPUMP + XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE))
	XMIN = ABS((YPUMP - XL*SIN(ANGLE))/(DXPUMP + XL*COS(ANGLE)))
	IF(DXPUMP.LT.0.0)
     2  XMIN=ABS((YPUMP-XL*SIN(ANGLE))/ABS(ABS(DXPUMP) - XL*COS(ANGLE)))	 
	PHIMIN = ATAN(XMIN)
	IF(DXPUMP.LT.0.0.AND.XL*SIN(ANGLE).LT.YPUMP) PHIMIN=3.1416-PHIMIN
      PHIMAX = ATAN(XMAX) 
	IF(DXPUMP.LT.0.0) PHIMAX = ANGLE
	EPUMP = (PHIMIN+PHIMAX)/3.1416
	IF(XL*SIN(ANGLE).GT.YPUMP) EPUMP = (PHIMAX-PHIMIN)/3.1416
	GEOM2 = GEOM2 + EPUMP*DELTA
50	CONTINUE
	GEOM2 = GEOM2/(BETAG*(XLPAR-XLPERP-DELLT))
	GOTO 75
C	SEPARATRIX + EP*DELN PASSES THROUGH RING--CASE 5
60	GEOM1 = 1.0 
	GEOM2 = ((YPUMP/SIN(ANGLE))-BETAG*DELLT)/
	2        (BETAG*(XLPAR-XLPERP-DELLT))		
75	HGEOM1 = BETAG*DELLT*SIN(ANGLE)/YPUMP
	IF(HGEOM1.GT.1.0) HGEOM1 = 1.0 
	HGEOM2 = 1. - HGEOM1 

	RETURN
	END