	SUBROUTINE RADINTG
C		INTEGRATES dLZ/dT WEIGHTED BY J0 OVER RADIUS
	DOUBLE PRECISION TEDP,XLZ1DP,DLDT1DP,XLZ2DP,DLDT2DP 
	INCLUDE 'soldiv.FI'
C		PLASMA CURRENT IN AMPS
	PLASMACUR = 1.E6*PLASMACUR 
	DENOMC = -0.062
C		DENOMC = J1(5.5)/5.5 THE DENOMINATOR OF < > OF EQ.(15)
	DELC = 1./56.

C	SE = SQRT(0.5*(1.+ELONG**2)) 
C      DELC = (1.0-DELTB/(AMINOR*SE))/56.0
	RHO(1) = 0.5*DELC
C	TE(1) = TPED + (T0-TPED)*((1.0 - (RHO(1)**2))**ALPHAT)
C	XNC(1) = XNPED + XNPED*(XNCTRPED-1.)*((1.0 - (RHO(1)**2))**ALPHAN)
	VOL = 2.*(3.14159**2)*RMAJOR*(AMINOR**2)
	HBEAMAV = PBEAM*1.0E6/VOL 
	CURDENAV = PLASMACUR/(3.14*(AMINOR**2))
C		C1 CONVERTS ERGS-cm^3 TO JOULES-m^3
	C1 = 1.0E-13 
	ETA = (8.85E-4)*ZEFFC/(TE(1)**1.5)
	CURDEN(1) = (PLASMACUR/(6.28*(AMINOR**2)))*(TE(1)**1.5)
	POHM(1) = -1.5*ETA*(CURDEN(1)**2)/TE(1)
	HOHM = POHM(1)*RHO(1)*DELC
	C3 = (TE(1)**1.5)*RHO(1)*DELC
	PB(1) = HBEAMAV*EXP(-0.5*((RHO(1)-RHOGAUSS)/SIGMA)**2)
	TEDP = TE(1)
	CALL CEFITS(NZIMP1,TEDP,XLZ1DP,1,DLDT1DP)
	if(nzimp1.eq.4.or.nzimp1.eq.6.or.nzimp1.eq.74) then
	xF0 = FNO(1)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP1,TEDP,xF0,XLZ1DP,DLDT1DP,ZAV) 
	endif
 	CALL CEFITS(NZIMP2,TEDP,XLZ2DP,1,DLDT2DP)
	if(nzimp2.eq.4.or.nzimp2.eq.6.or.nzimp2.eq.74) then
 	xF0 = FNO(1)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP2,TEDP,xF0,XLZ2DP,DLDT2DP,ZAV) 
	endif
	DLZDT(1) = FZ1*DLDT1DP + FZ2*DLDT2DP
C		(eV/erg)(m^3/cm^3) = 1.6e-6
	C8 = 1.6E-6 
	DLZDT(1) = DLZDT(1) + FNCOLD(1)*1.5*SVATPED*C8
	RAD = DLZDT(1)*RHO(1)*DELC
	DHDT(1) = -1.5*PB(1)/(TE(1))
	HEAT = DHDT(1)*RHO(1)*DELC
	BEAMPOW = PB(1)*RHO(1)*DELC

	DO 25 I = 2,56
	RHO(I) = RHO(I-1) + DELC
	X = RHO (I)
	CALL BESJ0(X,BES)
C	TE(I) = TPED + (T0-TPED)*((1.0 - (RHO(I)**2))**ALPHAT)
C	XNC(I) = XNPED + XNPED*(XNCTRPED-1.)*((1.0 - (RHO(I)**2))**ALPHAN)
	ETA = (8.85E-4)*ZEFFC/(TE(I)**1.5)
 	CURDEN(I) = (PLASMACUR/(6.28*(AMINOR**2)))*(TE(I)**1.5)
	POHM(I) = -1.5*ETA*(CURDEN(I)**2)/TE(I)
	HOHM = HOHM + POHM(I)*BES*RHO(I)*DELC
	C3 = C3 + (TE(I)**1.5)*RHO(I)*DELC
	PB(I) = HBEAMAV*EXP(-0.5*((RHO(I)-RHOGAUSS)/SIGMA)**2)
	TEDP = TE(I)
	CALL CEFITS(NZIMP1,TEDP,XLZ1DP,1,DLDT1DP)
	if(nzimp1.eq.4.or.nzimp1.eq.6.or.nzimp1.eq.74) then
	xF0 = FNO(I)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP1,TEDP,xF0,XLZ1DP,DLDT1DP,ZAV) 
	endif
	CALL CEFITS(NZIMP2,TEDP,XLZ2DP,1,DLDT2DP)
	if(nzimp2.eq.4.or.nzimp2.eq.6.or.nzimp2.eq.74) then
	xF0 = FNO(I)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP2,TEDP,xF0,XLZ2DP,DLDT2DP,ZAV) 
	endif
	DLZDT(I) = FZ1*DLDT1DP + FZ2*DLDT2DP

	DLZDT(I) = DLZDT(I) + FNCOLD(I)*1.5*SVATPED*C8
	DDLZ = DLZDT(I)
	RAD = RAD + DLZDT(I)*BES*RHO(I)*DELC
	DHDT(I) = -1.5*PB(I)/(TE(I))
	DDHDT = DHDT(I)
	HEAT = HEAT + DHDT(I)*BES*RHO(I)*DELC
	BEAMPOW = BEAMPOW + PB(I)*RHO(I)*DELC
	DZ = FZ1*DLDT1DP + FZ2*DLDT2DP

25	CONTINUE
	RHO(57) = RHO(56) + 0.5*(DELC+DELTB)
      X = RHO(57)
	CALL BESJ0(X,BES) 
C	TE(56) = TPED 
	TEDP = TE(57)
	ETA = (8.85E-4)*ZEFFC/(TE(57)**1.5)
  	CURDEN(57) = (PLASMACUR/(6.28*(AMINOR**2)))*(TE(57)**1.5)
	POHM(57) = 1.5*ETA*(CURDEN(57)**2)/TE(57)
	HOHM = HOHM + POHM(57)*BES*RHO(57)*DELTB
	C3 = C3 + (TE(57)**1.5)*RHO(57)*DELTB
	PB(57) = HBEAMAV*EXP(-0.5*((RHO(57)-RHOGAUSS)/SIGMA)**2)
	CALL CEFITS(NZIMP1,TEDP,XLZ1DP,1,DLDT1DP)
	if(nzimp1.eq.4.or.nzimp1.eq.6.or.nzimp1.eq.74) then
	xF0 = FNO(57)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP1,TEDP,xF0,XLZ1DP,DLDT1DP,ZAV) 
	endif
	CALL CEFITS(NZIMP2,TEDP,XLZ2DP,1,DLDT2DP)
	if(nzimp2.eq.4.or.nzimp2.eq.6.or.nzimp2.eq.74) then
 	xF0 = FNO(57)
  	if(xf0.lt.1.e-5) xf0 = 1.e-5
	CALL CXRCEFITS(NzIMP2,TEDP,xF0,XLZ2DP,DLDT2DP,ZAV) 
	endif
	DLZDT(57) = FZ1*DLDT1DP + FZ2*DLDT2DP
	DLZDT(57) = DLZDT(57) + FNCOLD(57)*1.5*SVATBAR*C8
	RAD = RAD + DLZDT(57)*BES*RHO(57)*DELTB
	RAD = C1*RAD/DENOMC
	PB(57) = HBEAMAV*EXP(-0.5*((1.0-RHOGAUSS)/SIGMA)**2)
	DHDT(57) = -1.5*PB(57)/(TE(57))
	HEAT = HEAT + DHDT(57)*BES*RHO(57)*DELTB	
	BEAMPOW = BEAMPOW + PB(57)*RHO(57)*DELTB 
      BEAMPOW = BEAMPOW*((6.2832*AMINOR)**2)*RMAJOR
	RAT = 1.0
	IF(PBEAM.GT.0.0) RAT = PBEAM*1.0E6/BEAMPOW
	HEAT = HEAT*RAT/DENOMC
	HOHM = HOHM/(DENOMC*(C3**2))
C		DIVIDE BY BOLTZMAN CONSTANT TO CONVERT TO UNITS m^3/s
	RAD = RAD/1.6E-19
	HEAT = HEAT/1.6E-19	
	HOHM = HOHM/1.6E-19
C		COMBINE OHMIC & BEAM HEATING INTO HEATING TERM
	HEAT = HEAT + HOHM		
	DO 50 I = 1,56
	POHM(I) = POHM(I)/(C3**2)
	PB(I) = PB(I)*RAT
	DHDT(I) = DHDT(I)*RAT
	DLZDT(I) = C1*DLZDT(I)
50	CONTINUE 
C		PLASMACUR IN MA
	PLASMACUR = 1.E-6*PLASMACUR 
	RETURN
	END

C		PBEAM DISTRIBUTED AS GAUSSIAN ABOUT RHOGAUSS
C		RAD IN UNITS m^3/s
C		HEAT IN UNITS m^3/s
C		DLZDT & DHDT IN UNITS OF W-m^3/eV

