	SUBROUTINE SECONDSTAB
	INCLUDE 'SOLDIV.FI'

C	COLLISION FREQUENCIES
C		COULOMB LOGARITHM
      Y = 25.3 - 1.15*LOG10(1.E-6*XNBAR) + 2.3*LOG10(TBAR)
 	IF(TBAR.LT.50.) Y = 23.4-1.15*LOG10(1.E-6*XNBAR)+3.45*LOG10(TBAR)
C		EFFECTIVE Z
	ZBAR = 1. + FZINTRIN*IZINTRIN + FZINJECT*IZINJECT 
C		COLLISION FREQUENCIES
	XNUI = 6.6E17*SQRT(XNATOM)*((1.E-3*TIBAR)**1.5)/
     2		(XNBAR*(ZBAR**4)*Y)		
	XNUI = 1./XNUI
	XNUE = 1.09E16*((1.E-3*TEBAR)**1.5)/(XNBAR*(ZBAR**2)*Y)
	XNUE = 1/XNUE
C		NORMALIZED COLLISION FREQ
	XNUIS = XNUI*Q95*RMAJOR/
	2		(((AMINOR/RMAJOR)**1.5)*SQRT(XK*TIBAR/XMASS)) 
	XMASSE = 9.1E-31
	XNUES = XNUE*Q95*RMAJOR/
 	2		(((AMINOR/RMAJOR)**1.5)*SQRT(XK*TEBAR/XMASSE))
C	COLLSION CONSTANTS
	SE = SQRT(0.5*(1.+ELONG**2)) 
	EP = AMINOR*SE/RMAJOR
	X = SQRT(2.*EP)     
      DCONST = 2.4 + 5.4*X + 2.6*(X**2)
	CQ1 = (4. + 2.6*X)/((1.+1.02*SQRT(XNUES)+1.07*XNUES)*
     2		(1.+1.07*(EP**1.5)*XNUES))
      CQ2 = (TIBAR/TEBAR)*CQ1
	CQ3 = (7.0+6.5*X)/((1.+.57*SQRT(XNUES)+.61*XNUES)*
     2		(1.+.61*(EP**1.5)*XNUES)) - 2.5*CQ1
      DD = 1.17/(1.+.46*X)
	CQ4 = ((DD+.35*SQRT(XNUIS))/(1.+.7*SQRT(XNUIS)) +
	2	2.1*(EP**3)*(XNUIS**2))*(CQ2/((1.+(EP**3)*(XNUIS**2))*
     3		(1.+(EP**3)*(XNUES**2))))
	BPOL = PLASMACUR*1.257/(6.28*AMINOR*SE) 
	XJAV = 1.E6*PLASMACUR/(3.14*(AMINOR**2)*ELONG) 
C		SINGLE NULL TRIANG FOR DIVERTOR HALF
	TRIANGAV = 0.5*TRIANG
	PSOL = 2.*XK*XNSOL*TSOL
 	PPED = 2.*XK*XNPED*TPED

	PRESSTB = 0.5*(PSOL + PPED)
	SE = SQRT(0.5*(1.+ELONG**2))
		
C	BOOTSTRAP CURRENT MIYAMOTO'S FORMULA WITH COLLISIONAL CORRECTION
	CONST = 0.5
	BETAPOL = PRESSTB/((BPOL**2)/2.514E-6)
   	FNU = 1./(1.+SQRT(XNUIS))
	GFAC = (1.+(ELONG**2)*(1.+2.*(TRIANGAV**2)-1.2*(TRIANGAV**3)))*
  	2		(1.17-0.65*EP)/((1.-(EP**2))**2)
 	HFAC = ELONG*(1.+(ELONG**2))/(SQRT(EP)*(GFAC**2))
	XT = TIBAR/TEBAR
 	GAMN = 1.
	GAMI = XT/(1.+XT)
	GAME = 1./(1.+XT)

	XLPMINUS = (1./XLNBAR) + (GAME/XLTEBAR) +(GAMI/XLTIBAR)
	XJBSMIY = 0.5*SQRT(EP)*AMINOR*ELONG*XLPMINUS*BETAPOL*FNU
	XJBSMIY = 0.5*XJBSMIY*XJAV
	SHEARMIY = SHEAR0 - 2.*XJBSMIY/XJAV
C	SECOND STABILITY ACCESS FACTOR ASSMIY *********************
	ASSMIY = ASS
	 
	FACK = HFAC*CSHEAR/CONST
	FACKMIY = FACK*FNU*ASS 
	GEOMFAC = EP*(GFAC**2)/(1.+ELONG**2) 
	
	XLMHDMIY = CONST*BETAPOL*GEOMFAC*AMINOR*(1.+FACKMIY)/
	2			(CSHEAR*ASSMIY*SHEAR0)
	
C	NOMINAL W/O BOOTSTRAP CURRENT
	XLMHDNOM = XLMHDMIY*ASS/(1.+FACK) 
C	BOOTSTRAP CURRENT WESSON'S FORMULA
	XJBSWES=(0.5*SQRT(EP)*AMINOR*ELONG*BETAPOL*1.414/DCONST)*
	2		(CQ1*XLPMINUS + (CQ3/XLTEBAR) +(CQ4/XLTIBAR))
	XJBSWES = 0.5*XJBSWES*XJAV
C	SHEAR
	SHEARWES = SHEAR0 - 2.*XJBSWES/XJAV
C	SECOND STABILITY SHAPE FACTOR & ACCESS FACTOR ****************
	ASSWES = ASS
	FACKWES = FACK*ASSWES*1.414*CQ1/DCONST 
						  	
	ZZ = 0.5*SQRT(2.*EP)*AMINOR*ELONG*GAME*BETAPOL/DCONST
	XLMHDWES = CONST*BETAPOL*GEOMFAC*AMINOR*(1.+FACKWES)/
	2		(CSHEAR*ASSWES*(SHEAR0-ZZ*((CQ3/XLTEBAR)+(CQ4/XLTIBAR))))

C	MHD BALLOONING MODE STABILITY INDICES
	BALWES = XLMHDWES*XLPMINUS 
	BALMIY = XLMHDMIY*XLPMINUS
	BALNOM = XLMHDNOM*XLPMINUS
	RETURN
	END