	SUBROUTINE WIDTH 
	INCLUDE 'SOLDIV.FI'
	real deln2v
c		CALCULATES WIDTHS OF SOL USING BOHM RADIAL TRANSPORT
	DEL = (5.*ALB*XK*XNSEP*(TSEP**2)/(32.*B*FLUXHEAT))
	CHIBOHM = (5./32.)*ALB*TSEP/B
	DELN = DELRATNT*DEL
	GOTO 75
C		BOUNDS ON DELN
	IF(DELN.GT.DELNMIN) GOTO 25
	DELN = DELNMIN
25    IF(DELN.LT.DELNMAX) GOTO 50
	DELN = DELNMAX
50	DEL = DELN/DELRATNT

75	DELT = DEL
	DELEA = 2.*DEL/7.
	DELNV = DELN/(1.+DELRATNV)
	DELNT = DELN/(1.+DELRATNT)
	DELN2V= DELN/(1.+2.*DELRATNV)
C		SET INNER & OUTER SCRAPEOFF LAYER THICKNESSES
	DELN1 = DELN
	DELN2 = DELN
	EPDIV1 = EPDIV
	EPDIV2 = EPDIV 
C		SET OPENING BETWEEN PL & SPL OUTBOARD
c	DELX = DELXREAL - DELN 
	delx = delxreal 
100	RETURN
	END